from . import appstream
from . import braket
from . import certificatemanager
from . import cloud9
from . import cloudfront
from . import cloudtrail
from . import cloudformation
from . import cloudwatch
from . import codeartifact
from . import codebuild
from . import codecommit
from . import codegurureviewer
from . import codepipeline
from . import cognito
from . import comprehend
from . import configservice
from . import databrew
from . import dataexchange
from . import datapipeline
from . import dynamodb
from . import ec2
from . import ecs
from . import efs
from . import eks
from . import elasticbeanstalk
from . import elasticcache
from . import elasticinference
from . import elasticloadbalancing
from . import emr
from . import emrcontainers
from . import events
from . import es
from . import forecast
from . import frauddectector
from . import fsx
from . import glacier
from . import glue
from . import greengrass
from . import iam
from . import iotanalytics
from . import iotevents
from . import kafka
from . import awslambda
from . import kinesisanalytics
from . import kinesis
from . import kms
from . import macie
from . import mq
from . import opensearchservice
from . import organizations
from . import qldb
from . import ram
from . import rds
from . import redshift
from . import resourcegroups
from . import robomaker
from . import route53
from . import route53resolver
from . import sagemaker
from . import secretsmanager
from . import s3
from . import ses
from . import sqs
from . import sns
from . import ssm
from . import stepfunctions
from . import storagegateway
from . import workspaces